#import "../lib/resume.typ"

// Resume

#resume.full(
  head: resume.header(
    name: "Toufiq Abir Farhan Tufan",
    address: "B3L 1J8, Halifax, NS, Canada",
    links: (
      link("tel:+1 (902) 817-8338"),
      link("mailto:toufiqabir5@gmail.com"),
      link("https://abir866.github.io/my-porfolio/", "my-porfolio"),
      link("https://www.linkedin.com/in/toufiq-abir-farhan/", "linkedin.com/in/toufiq-abir-farhan"),
      link("https://github.com/Abir866/", "github.com/Abir866"),
    ),
  ),
  profile: "Passionate and solution driven customer service representative with over 3 years of expereince in customer service and sales in a client facing settings. Friendly , professional behaviour at every customer interactions, building rapport and driving results by making purchase recommendations. Present producta that not only meet customer needs but overall client get an expectional service through out the purchase process by guidig the customer at every step going above and beyond to make the interation feel personalised. Ability to utlize standard scripts and adapt communication to effectively solve customer inquiries. Document information to keep records for reference and access them as deemed by situation. Confident in using communication strategies that attract customers attention to the value company provides through respective products.",

education: (
  resume.education(
    institution: "Saint Mary's University",
    location: "Halifax, NS",
    program: "Bachelor of Science",
    major: "Computer Science",
    start: "Sep 2020",
    end: "May 2024",
    courses: (
      "Intro to Computer Applications",
      "Data Management",
      "Microeconomics",
    ),
  ),
),

experience: (

  resume.experience(
    company: "Atlantic Superstore",
    location: "Halifax, NS",
    role: "Customer Service Representative",
    start: "Sep 2025",
    end: "Present",
    points: (
      "Provide support to customer during solving product exchange issues by leadng converstation following a flow guide to ask relevant questions increasing efficiency to properly complete resolution procedure while adpating tone accordingly to make the interaction more humanly",
      "Sold wide range of products from processed , fresh, frozen food items by understanding customer's travel needs and connecting the prodcct with features that stasfies the requirements thus providng personalizing customer experience",
      "Offer additional complimentary products as recommendations that can improve the experience with the orginal product whereas keeping it customer's budget friendly",
      "Communicated with customers in a friendly, natural manner, adapting to their energy and comfort level to ensure a positive and respectful interaction.",
      "Convince customers to purchase a higher-end product by appealing to features that makes it better than other versions and more suited to meet clients expectations",
      "Engaged with university students across various areas, faculty and level to understand their academic challenges, offering tailored subject matter advice and identifying opportunities for further enhancing their learning experience, which built trust and long-term satisfaction with tutoring services."
      "Anticipated the need for scheduling multiple tutoring sessions at crucial times by following up  by phone calls to inquire about the student’s course materials and exam schedules. Planned and managed online Microsoft Team meetings in advance for facilitating the student’s preparations and maximizing the student’s results",
      "Guided students in their study program based on previous academic experience including planning courses to take each semester under which professor at the university that best aligns with their career goals and rewarding learning experience",
      "Worked one-on-one with individual students from various faculty and levels, conducting orientations to discuss their goals, strengths, and weaknesses in specific topics of the course. Evaluated their needs to create tailored strategies that allows them to appreciate learning helping them succeed in meeting their objectives",
      "Retrieved all past online meeting call recordings through transfer request from Microsoft as  third party meeting hosting platform and retaining in local system for long term access during auditing operations of disputes",
      "Adopted an adaptive teaching approach by leveraging technical tools such as coding platforms, visual diagram softwares tailoring instruction to accommodate diverse learning styles and optimize individual student outcomes",
      "Monitored student behavior during study sessions, noticing any disruptive issues with personal attitude due to academic stress. Motivating the student before the exams by celebrating his achievements",
      "Managed time to provide after-hours email support to address additional questions and concerns",
      "Recommended additional teaching materials to reinforce student’s confidence in a concept",
      "Maintained a strong, supportive relationship, resulting in the student seeking my expert services for over a year, relying on my help for various academic courses",
      "Managed onboarding of members by preparing a checklist of office activities- setting up individual account access to one workplace platform, upgrading work devices and assigning training modules to 60 new intakes from various departments and track results of strengths, and weaknesses for balanced team formations. Evaluated the need to create tailored strategies that allows each person to appreciate learning helping them succeed in meeting their team objectives",
      "Review detailed report on individuals for address eligibility requirements to create accounts ensuring compliance with legal guidelines",
      "Communicated in writing (email, text, or cat) with students regarding their motivation for contact, maintaining welcoming and supportive attitude at all times and provide follow-up communications to gather feedback, identifying areas of improvement throughout the grading resolution journey towards completion",
      "Clarified student inquiries about tutor meetings by providing detailed information on session topics, objectives, and expectations, ensuring they arrived well-prepared for a focused and meaningful learning experience.",
      "Deployed targeted outlook follow-up email campaigns to student after every tutoring session, reviewing discussed topics, sharing additional learning materials, track progress, maintaining student engagement in the course - retaining all students over 2 years while expanding the group through referrals",
      "Maintaining orderliness and tidiness of workspaces at the end of each tutoring session prevents any disruptions in commencing upcoming meetings and creates an welcoming impression",
      "Assist student training through encouraging pursue of certifications, book and schedule meetings with industry professionals, assign access to courses for introductory training, tracking attendance and send follow-up emails to nurture student growth by attaining applicable skills"
    ),
  ),
  
    resume.experience(
    company: "Saint Mary's University",
    location: "Halifax, NS",
    role: "Computing Science Tutor",
    start: "Sep 2023",
    end: "Jun 2024",
    points: (
      "Clarified needs through guided questions to identify the purpose of each request, allowing accurate and personalized support",
      "Tracked and followed up on open issues by maintaining records and checking resolution status, ensuring no cases were left unresolved",
      "Multitasked effectively by managing multiple students, communication channels, and deadlines simultaneously, meeting service expectations in a fast-paced environment",
      "Guided students with their assignments by breaking down the problem into manageable steps allowing them to understand the solution as they complete the task accurately.",
      "
    ),
  ),
    resume.experience(
    company: "Saint Mary's University",
    location: "Halifax, NS",
    role: "Operations Assistant",
    start: "Jan 2023",
    end: "Apr 2024",
    points: (
      "Responded to high volumes of inbound email and call inquiries by actively listening, asking structured clarifying questions, and following standardized procedures, ensuring accurate resolution and positive service experiences aligned with customer satisfaction goals",
      "Determined student needs by using question-and-answer techniques to understand student concerns and service expectations, allowing appropriate guidance and first-contact resolution",
      "Greeted and engaged faculty participants in a courteous, professional manner during live calls, building trust and maintaining a welcoming ad comfortable environment",
      "Processed requests accurately by documenting inquiry details, outcomes, and follow-ups in tracking systems, supporting case closure and service quality standards",
      "Adhered to scripts and policies by communicating approved information when required, ensuring compliance with institutional standards and consistency in service delivery",
      "Delivered greetings to the professors and colleagues in a friendly and professional manner at the start of each TA group meeting, demonstrating a welcoming attitude that builds a respectful and comfortable environment.",
      "Supported students in their web development assignments for an e-store site by identifying errors in the structure and layout of product pictures. Guided them to organize and arrange content adhering to the planned acceptable layout, ensuring discounted products, seasonal products, and special offers were visually grouped in their designated placements as part of promotional spaces.",
      "Supported students in web development assignments by breaking down coding issues affecting content presentation and explaining design concepts in reference to their familiar course materials, connecting their hands-on experience with theory to enhance learning.",
      "Retrieved all student assignment grades in course management software reconciling any grade changes in assignments, to enter in Excel grade sheets and verifying information in both software and grade sheets to provide accurate records to the professor following company policies and procedures",
      "Remained informed of inbound emails by regularly monitoring the Outlook inbox to ensure that no important communication from the professor regarding updates to the web page design plan was missed, enabling timely adjustments to grading requirements for the valid structure.",
      "Forwarded relevant email conversations with the professor as a contact point to the rest of the TA colleagues to keep them informed and answer their related meeting questions bridging communication gaps between parties",
      "Documented monthly reports of individual student assignment grade changes and specifics of their mistakes in a Word file, focusing on reflection of student performance to the professor in a structured and clear manner",
      "Handled student complaints about marking with empathy and sincerity, ensuring a clear understanding of the basis of concern to address appropriate response. Elevated the grievance with proper details informing the professor and booked the student a meeting with the management for providing further consultation and implementation of the solution",
      "Calculated and logged work hours in Excel files by observing each student’s project schedules of time entries  for the entire semester, ensuring each student met the minimum attendance hours required to qualify for a grade",
      "Troubleshoot student software assignments for hardware and networking issues by manually testing HTML, JavaScript, and other web-based applications, as well as addressing assignments involving networking or hardware issues to ensure accuracy, functionality, and performance of 60 assignments per month",
      "Managed administrative responsibilities such as tracking student attendance, logging assignment grades, and preparing progress reports of individuals for academic oversight when final grades are discharged.",
      "Coordinated and maintained communication with students and professors through email and Microsoft Teams, sharing student records ensuring all students’ course progress reports were accessible with latest information",
      "Analyzed students’ submissions against grading criteria during complaint resolution, investigating alternative ways to give mutually beneficial feedback after the recheck procedure that helps students understand that the resulting solution is of the student’s best interest  while avoiding further escalation of the issue",
      "Ensured student’s compliance with academic policies by flagging and reporting overdue submissions to the professor for timely regulatory action against the student",
      "Managed grade sheets by transferring marks from Brightspace software to Excel, ensuring information integrity",
      "Recorded assignment resubmission requests of five students received by email and in-person from the professor, ensuring only the latest submissions were identified from the  assignment dropbox for grading by the TA team",
      "Graded code assignments submitted by students for performance and accuracy involving identifying and tracking of bugs,  and thoroughly documenting mistakes for students. Suggested feedback of corrections and alternative ways to avoid errors from occurring, marked over 60 student assignments per month",
      "Actively managed inbound communications from professors, students and colleagues, responding to emails and messages answering their questions  to ensure smooth information flow",
      "Proactively identified prospective students from the learning platform’s database requiring assignment resubmission. Used outbound email contact to notify them of deadlines, preventing disqualification and ensuring 100% of the students maintained academic progress",
      "Encouraged active student engagement by facilitating interactive group discussions and asking thoughtful questions about lecture topics. Guided students to assess their understanding and inspired them to conduct independent research to deepen their knowledge and built a sense of ownership on learning",
      "Established a standard grading scheme after discussing with the teaching assistant team to mark student assignments complying with the given criteria ensuring fairness in grading for all students",
      "Organized technical documents received from students electronically in a computerized file system, labeling  each file  under the respective student folder with metadata of submission time, version number for correctly  tracking of files from the log of information when grading",
      "Captured student feedback regarding online assignment grade evaluation services, understanding their concerns calmly to escalate to the appropriate departmental professor , providing the given recommendations to enhance online grading services allowing students to enjoy online classes",
      "Managed assignment postings process in course management software and distributed email notices to advertise a 24/7 student discussion forum, improving access and engagement with academic content",
      "Recognized risk scenarios associated where feature change requests pending under the client profile, impacting project delivery dates, immediately escalating details to the client service team to trigger a review confirming risks and mitigation strategies before software development commences",
      "Maintained software feature quality and production targets of number of features ensuring the software requirements agreement defined by the business are met, full-filling expectations",
      "Log and track progress of student support tickets, keeping records of their software roadblocks and  issues, following-up the report to correct department for in time resolution",
      "Managed confidential academic files, securely filing exam papers, assignments, and evaluation records in accordance with university document-retention policies",
      "Performed key control oversight activities of all the back office activities related to effective dispute resolution including review process fairness and accuracy of solution, duration and trends in complaints for reporting to management",
      "Assist the information recording team in creating information letters, manuals and up-to-date FAQ resources as guideline for appropriate product usage by customers based on insights derived from customer survey feedback  and during every hands-on demonstration of newly developed product features, ensuring accurate information is disseminated to users reducing the number of support requests due to self-serve",
      "Completed due diligence checks on references in assignments for plagiarism, AI use and citation accuracy to ensure compliance with integrity standards",
      "Supporting the department head throughout the student application intake process by logging in timeline data to track the progress in procedural steps and updating individuals through email to ensure steps are followed",
      "Support teammates performance review life cycle by tracking group activity towards the scheduled deadline of a team project using team management software, completed member evaluation document and coordinate with managers timely to get the pending reports submitted that provide insights into performance of members and relay that as goal for next period",
      "Assisted in client registration service into the course as guide to filling out forms with necessary details, clarifying documents to be signed, retaining and sharing copies of documents to students for reference, and correspond with students during the intake process with updates needed to access the course content as a commitment to provide  smooth onboarding service experience",
      "Performed receptionist duties for staff, professors, students with welcoming attitude and positive interpersonal skills to direct individuals to appropriate departments, hand out appropriate materials for pickup and note down any requests, prioritizing for immediate action.",
      

    ),
  ),
    resume.experience(
    company: "Saint Mary's University",
    location: "Halifax, NS",
    role: "Administrative & Data Coordination Support",
    start: "Sep 2022",
    end: "Jul 2024",
    points: (
      "Answered inquiries accurately by referencing internal documentation and knowledge bases, ensuring reliable and consistent responses to client questions",
      "Researched options by gathering and validating client requirements, reviewing system capabilities, and comparing feasible solutions, enabling informed recommendations aligned with client expectations",
      "Answered inquiries accurately by referencing internal documentation and knowledge bases, ensuring reliable and consistent responses to client questions",
      "Documented transactions and updates by recording client decisions, changes, and approvals in project records for reference to support accurate execution by other teams and promote accountability.",
      "Worked one-on-one with the client to deliver a sales-pitch style presentation suggesting new product features, sharing product knowledge to ensure her clarity of its potential to enhance the product's engagement for younger audiences",
      "Visited the client’s conservation site to understand its unique offerings and develop strategies to enhance the website’s content, effectively showcasing the natural products and historical significance of the area to attract potential stakeholders and drive her sales; strengthening the region’s  preservation",
      "Identified trends in user reports of software online service recovery request incidents and after investigation finding the unwarned server program shutdown to be the root cause. Proactively recommended the development team to implement a visible maintenance error message to users as a solution, avoiding  reoccurrences of related complaints entirely",
      "Addressed client’s insights about software upgrade and offered guidance following standard procedure necessary to streamline the client’s feature  request process  to the development team elevating her customer experience"
      "Recognized risk scenarios associated where feature change requests pending under the client profile, impacting project delivery dates, immediately escalating details to the client service team to trigger a review confirming risks and mitigation strategies before software development commences",
      "Maintained software feature quality and production targets of number of features ensuring the software requirements agreement defined by the business are met, full-filling expectations",
      "Assisted with the on-boarding of new teammates for the software project by setting up individual accounts to one workspace platform , upgrading working devices’ for running the project locally and syncing access to limited server resources for effective collaboration",
      "Kept professor informed on the status of his grading requests through regular email providing clear and helpful updates allowing him to take appropriate steps",
      "Contributed to the project’s knowledge base by writing an installation manual using office 365 for the software including documenting  common fixes, and best practises to avoid bugs and gain the ultimate user experience",
      "Contributed in a team of 6 developers performing tasks as assigned of maintaining client communications, collecting feedback through meetings and informing the team for enhancements in the product ensuring they meet client expectations",
      "Led job allocation for each member in a team of six having diverse academic backgrounds and experience, following up with consistent communication to track each member’s progress, allowing adjustments in priorities of the team’s schedule to consistently meet the planned production output",
      "Assigned jobs  for each member that highlighted each other’s unique talents , ensuring the sense of belonging and upholding team culture by encouraging contribution of individual perspective to strengthen the overall project plan",
      "Supported the development of a software project plan by collaborating with clients to identify and document feasible feature requirements. Ensured all requirements aligned with project scope, time constraints, and technical tools availability to facilitate smooth execution within the software development chain",
      "Deployment checklist for best practices including alignment of coding, documentation style and version control that allows collaborative contributions of the team towards quality software production",
      "Adopted project management tool such as gantt charts to track project milestones, ensure tasks are completed on time and weekly report on project progress in team meetings to resolve any blockers",
      "Created an automated build and testing workflow starting from production to deployment, identifying and tracking bugs for supporting fast reliable software release",
      "Coordinated with cross-functional Quality Assurance team through consistent communication to understand the team’s requirements to develop a middleware for the software  allowing seamless integration of the group’s  plan",
      "Collaborated with senior developers in strategy meetings gathering  insights to improve performance metrics by including bugs detected for each executable actions allowing software’s efficiency to increase 100% with no errors",
      "Maintained positive client relationships by consistently engaging directly to gather feedback with customer surveys on software upgrades, identifying areas for improvement, and addressing new needs. Secured opportunities for ongoing support by ensuring satisfaction with the software beyond the academic project timeframe",
      "Managed task allocation for each team member in the project schedules, followed up with consistent communication  to track their progress, allowing the team to make adjustments in schedule to meet the overall planned project monthly deadline date with finished deliverables",
      "Organized travel arrangements for the development team to  the client’s conservation site to listen, understand and administer appropriate strategies that improved the website’s content to showcase the historical significance of the area to potential stakeholders",
      "Assist in developing user manuals and conducting hands on demonstration sessions for new software implementation that allows stakeholders the understand the benefits and functionality of the upgrade",
      "Reassigned tasks among team members by evaluating availability and progress metrics of members, ensuring balanced workloads and timely project completion. Tracked each member’s contributions and updated  them of schedule changes  facilitating smooth collaboration",
      "Processed post meeting notes identifying pending client requirements and complete notifying action by creating follow-up email notifications regarding the notes in a structured manner to the rest of the development team, allowing implementation to begin immediately",
      "Resolve client’s software product upgrade inquiries by following standardized process while referencing internal knowledge base for unique situation to efficiently relay required information",
      "Gathered relevant information from client feedbacks and internal processes including client -support channel, prioritization and assignment  to develop metrics  marking the performance of each process and identifying the areas requiring improvement",
      "Assumed responsibility to actively monitor various communication medium including telephone to  collect details of products’ adverse effects to perform assessments following the defined error detection and eradication procedure to recover to normal functionality that is still maintained for years",
      "Maintained the entire customer and product database for client, recognizing the entity-relationships established between entries thus following the same  structured scheme  to ensure following data conform to the rules making complex update queries to be accurately applied  accurately on large group of data  reducing maintenance time to  one go",
      "Maintained and structured large customer and product databases by enforcing entity-relationship rules and writing complex update queries, improving data consistency and reducing maintenance time through accurate bulk updates.",
      "Performed literature search across the vast exclusive database for the department for various sources including medical journals  with systematic approach using topic specific keywords, synonyms  and comprehensive queries through  the support of advanced  filters, each time noting down the results and queries used, allowing to try new search methods progressively, to collect a wide range of  relevant sources for making informed decision regarding the topic question",
      "Supports entire  procedural document life-cycle starting from  creation in  sharepoint as a content management system to collaborate, share files and allowing to store department  documents and review through versions of changes  that significantly concentrates solely on quality assurance  instead of organization",
      "Drafted an outline of offer letter with all the necessary section with clarity including pay, schedule, and procedures for the client that aligns with standards and regulations followed by the management which acquired approval immediately to ensure a smooth timely process for the client to sign. ",
      "Lead onboarding and offboarding activities of first year students filing required confidential agreements and background checks following checklist for the entire academic life cycle of each member from the beginning and completion of course while being consistently connected with relevant IT and departments to implement changes to records associated with the student's reducing friction between each student transition ",
      "Responsible for updating student profiles on course management software based on an improved process workflow that synchronizes central student data changes on the software automatically to update grade sheet thus maintaining an accurate employee record across different platforms ",
      "Support team member transfers and promotion time to time in the development team with new delegations, assign new responsibilities and permissions under appropriate reporting manager, link to new training that aids in transition ",
      "Assist in welcoming new members into the society, going through each eligible benefit like insurance, in one-on-one sessions, gathering necessary details related to agreement forms to administer the perks while answering questions that improves understanding the importance for each benefit enrolment ",
      "Prepare client feedback reports as guideline to focus development efforts on specific areas for the team, through relevant data collection and organization that are clearly highlighted in the document compiling impact metrics with actionable suggestions",
    ),
  ),
),

skills-dict: (
  "Core Skills": (
    "Email & Phone Correspondance",
    "Friendly and Professional Behaviour",
    "Maintain knowledge base",
    "Adherence to standard scripts",
    "Production recommendations",
    "Complimentary sales",
    "Customer Service",
    "Relationship building",
  ),
  "Tools": (
    "Microsoft 365(Excel, Access database)",
    "Content Management Software",
    "Windows",
  ),
  "Strengths": (
    "Situational Awareness",
    "Calm Under Pressure",
    "Professional Presence",
    "Observational Skills",
    "Accountability",
  ),
 ),
)
